name: Code Quality

on:
  pull_request:
    branches: [ "master" ]

jobs:
  # --- BACKEND ANALYSIS ---
  backend-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, curl, libxml, zip
          coverage: none

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

      - name: Run Laravel Pint (Dry Run)
        run: ./vendor/bin/pint --test

      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse

      - name: Security Check
        uses: symfonycorp/security-checker-action@v5

      - name: PHP Insights
        run: php artisan insights --no-interaction --min-quality=80 --min-complexity=90

  # --- FRONTEND ANALYSIS ---
  frontend-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run ESLint (React Quality)
        run: yarn lint
